name: create-docs
on:
  push:
    branches: [main]
jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"

      - name: Install packages
        run: |
          cd docs
          yarn install

      - name: Set the homepage field to the Github Pages URL
        run: |
          cd docs
          jq '.homepage="https://vitreusx.github.io/teamder/"' package.json | sponge package.json

      - name: Build docs
        run: |
          cd docs
          yarn build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
