name: create-docs
on:
  push:
    branches: [main]
jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"

      - name: Install sponge
        run: |
          sudo apt-get install moreutils

      - name: Build docs
        run: |
          cd docs
          yarn install
          jq '.homepage="https://vitreusx.github.io/teamder/"' package.json | sponge package.json
          yarn build

      - name: Build Web version of the app
        run: |
          cd teamder
          yarn install
          jq '.homepage="https://vitreusx.github.io/teamder/web"' package.json | sponge package.json
          expo build:web

      - name: Copy the Web version to a subdirectory of the docs build
        run: |
          cp -r teamder/web-build docs/build/web

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
